language: java
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
  - "$HOME/.m2"
jdk:
- oraclejdk8
deploy:
  provider: script
  script: bash scripts/travis_deploy.sh
  on:
    tags: true
env:
  global:
  - BINTRAY_USER=philippotter
  - secure: riaDUHzF9JpXIGqKXFf7JSQYHM1nSHcqD/nDR0fePgK3G7Z1/ys2frS+mLuDD73XRvzP98mBeRVrI2QHcbYEspHNJA5p+GiSpSMCBdL9ullxfij3M+1GJ5NUXj62aHr7Fu6fVNmrao4ewXHXSDIR9CEjZluLT7ydio9mvVCgHf4tiZpnFk7RqGxupealm8ZDjyaa4hrffv5eEPmO1LVZT7rlxJ1aBxDy022WisM33KrD2xzz9tAtgt33ldF1Z5wD+v4Zk7WH1Fp9xxmJCfJTrGMI11Zqwt2jKt/1wxTMq7bOQIyCNvjC2zhCs+/Wl2fFuED8EGkzA3/4VL5dY9fpU3L81RXvpAjgepqGdB5VNe7CXKZpq+1wGYJ2j0Jm2sWSoYJz/CEcrfIR5V0WtNIcU9TGxrAXrsXEcnWnmILuE33uWBPlywLRCSGL0pVGMzlqxc+2l5dN6gKUmdHMEa32dOAZHI34MXk3YUQykY4oCX/FZCzhn3bS/LyYZYPbsHMvMFiEV4km3as4+TqA/8jJ6lOkdVOhTP08WZQmVCBrMoonGvnClLWK2Mk4gLXSEOwSgBnr6JyIhKx5CwmI4jFdO1x9CwFFmLtn2NlPAmeiuZZp5n4c8+phC3SeKel6sdezwimQF3A0jZLq6+ARcG/wd/WXVwjXmpkrSdg6sXnklpM=
