version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependabot"
    target_branch: "master"
    commit_message:
      prefix: "BAU"
